# SPDX-License-Identifier: Apache-2.0

name: Tests with Ollama backend
on:
  push:
    branches:
      - "main"
      - "release-**"
    paths:
      - 'src/**.py'
      - 'pyproject.toml'
      - 'tox.ini'
      - '.github/workflows/test_ollama.*' # This workflow
  pull_request:
    branches:
      - "main"
      - "release-**"
    paths:
      - 'src/**.py'
      - 'pyproject.toml'
      - 'tox.ini'
      - '.github/workflows/test_ollama.*' # This workflow

env:
  LC_ALL: en_US.UTF-8

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  test_ollama:
    name: "test-ollama: using ${{ matrix.python }} on ${{ matrix.platform }}"
    runs-on: "${{ matrix.platform }}"
    strategy:
      matrix:
        python:
          - "3.12"
        platform:
          - "ubuntu-latest"
    steps:
      - name: "Harden Runner"
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout
        uses: actions/checkout@v6

      - name: Free disk space
        uses: ./.github/actions/free-disk-space

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python }}
          cache: pip
          cache-dependency-path: |
            **/pyproject.toml

      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh>=1.2

      - name: Setup Ollama server
        uses: ./.github/actions/ollama-setup

      - name: Setup intrinsics on Ollama server
        uses: ./.github/actions/ollama-setup-intrinsics
        with:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}

      - name: Ollama tests
        id: testollamanotebooks
        run: |
          tox -e ollama
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
